### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/terraform-provider-clc#1]
i'm having issues with the windows build.  I assume i'm supposed to download the windows release and rename it with an .exe extension but doing so it seems like the exe is no good.  

```
C:\plans>terraform plan
←[31mError configuring: 1 error(s) occurred:

* fork/exec C:\terraform\terraform-provider-clc.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.←[0m←[0m
```

**Comment by ack** [comment]
thanks for the feedback, sorry I hadn't noticed these issues til just now. the binaries are only for 64-bit which it would seem this error message is complaining about. if you happen to be running on a 64-bit OS, it would be helpful to know: 
- full os version 
- `terraform version`
- whether `terraform plan` works at all for any of the builtin providers and if so, whether any other 3rd party releases work.

**Comment by chrislittle** [comment]
I'm on a 64bit Windows 7 PC.  i'm using 0.6.9 (latest)

I don't really have any accounts on any of the other providers to test anything.  

is there a reason the windows release is a no name file type?  its not an exe on download?  that seems odd.  its just a file with no extension named terraform-provider-clc.windows-amd64.  any windows file needs some type of extension to even be valid.

**Comment by ack** [comment]
Oh I see. Ya, I don't think you'll be able to run it without an .exe extension. Can you try renaming the binary to an .exe?

**Comment by chrislittle** [comment]
that's what i did since I assumed as much.  and thus the error.  i suspect your build of the exe is bad

**Comment by ack** [comment]
I'll see if I can ferret out the issue on a windows VM. Thanks.

**Comment by ack** [comment]
rebuilt and tested the windows binary by hand. give 'er a whirl

**Comment by chrislittle** [comment]
good to go now!

**Comment by caward24** [comment]
> I'll see if I can ferret out the issue on a windows VM. Thanks.
I know a lot of time has passed since then but what was the issue and how was it fixed.
