### ISSUE TITLE
storage types

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/terraform-provider-clc#3]
I don't see storage types field in the https://github.com/CenturyLinkCloud/terraform-provider-clc#clc_server documentation.  

thus any terraform apply plans fail with \* clc_server.srv: Failed creating server: http err: [400 Bad Request] - {"message":"The request is invalid.","modelState":{"body.storageType":["The field storag
eType must be hyperscale."]}}

i'd think for both hyperscale (hyperscale) and standard VM (std or premium) type you need an entry.  I tried a few variations without luck guessing.

**Comment by chrislittle** [comment]
fyi tried storageType, storagetype, storage-type etc.  per the API it should work (using a hyperscale VM) with 

```
storageType = "Hyperscale" 
```

**Comment by ack** [comment]
thanks, finally got around to adding this. sorry for the delay: 

https://github.com/CenturyLinkCloud/terraform-provider-clc/commit/4cc327193719efe9f470834ac061fca8f66423f4#diff-e4eb32956cc0792fc0de7be1576a87c6L77

Is your group set up with defaults? Odd that I never saw this error.

**Comment by chrislittle** [comment]
with the latest build just released on terraform.io there still seems to be a bug when you choose other than standard server type.  how do I input hyperscale properly into a plan?  when I choose 'type' to be hyperscale it errors.

Error applying plan:

1 error(s) occurred:
- clc_server.srv: Failed creating server: http err: [400 Bad Request] - {"message":"The request is invalid.","modelState":{"body.storageType":["The field storag
  eType must be hyperscale."]}}

I tried adding a field called storagetype in my plan but no luck

**Comment by ack** [comment]
did you try storage_type ?

admittedly, I didn't test with non-standard. :(

API docs say { standard | premium } for both fields so I'd try type:premium and storage_type:premium

**Comment by chrislittle** [comment]
bazinga!  can you put that in the readme in the server create area in case others come along and need that info?

**Comment by ack** [comment]
premium / premium worked?

**Comment by chrislittle** [comment]
if you do type=standard and storage_type=premium it works fine as expected.  for me it was just about getting the storage_type field right.
