### ISSUE TITLE
Go Test currently fails

### ISSUE THREAD

**Issue by fatmcgav** [CenturyLinkCloud/terraform-provider-clc#4]
Having downloaded the source code to try and make a couple of small modifications, it appears that a couple of the tests are failing. 

``` go
~/golang/src/terraform-provider-clc > master: # go test .
# terraform-provider-clc
./provider.go:57: not enough arguments in call to api.NewConfig
./provider.go:57: multiple-value api.NewConfig() in single-value context
FAIL    terraform-provider-clc [build failed]
```

**Comment by fatmcgav** [comment]
I've created a PR (#7) for the above with a possible fix, as it was preventing me from building my code locally...

**Comment by ack** [comment]
ya, the underlying sdk changed this interface and this project doesn't use godeps yet. the PR does though. I'l likely be deprecating this plugin once the plugin is mainlined. in the interim, i'll update and peg the version we want into godeps here.

**Comment by fatmcgav** [comment]
Looks good, cheers...
