### ISSUE TITLE
Server password should be optional

### ISSUE THREAD

**Issue by fatmcgav** [CenturyLinkCloud/terraform-provider-clc#8]
As per the API, the `password` property is non-mandatory, and if not specified a password will be generated upon creation. 

This should be reflected in the Terraform provider so that users don't have to worry about generating/storing passwords for servers in config files...

**Comment by tonycapone** [comment]
I second this. I'd prefer to use the unique password generated by CLC.

**Comment by fatmcgav** [comment]
@tonycapone The CLC provider is in Terraform core now. 

I've just raised this PR against Terraform - See https://github.com/hashicorp/terraform/pull/6414

Will go and close this issue as superseded.
